In [27]:
from dotenv import load_dotenv
import os 
from google import genai

load_dotenv()

client = genai.Client()

response = client.models.generate_content(
    model = "gemini-2.5-flash", contents="Tell me a programming joke"
)

response

GenerateContentResponse(
  automatic_function_calling_history=[],
  candidates=[
    Candidate(
      content=Content(
        parts=[
          Part(
            text="""Why do programmers prefer dark mode?

Because bugs are attracted to light!

---

Or, a classic:

A programmer is debugging some code. They've been stuck for hours, unable to find the problem. Frustrated, they call over a colleague and say, "I've tried everything! Can you just watch me walk through the code and tell me if you see anything?"

The programmer starts explaining the code line by line, detailing the logic and variables. About halfway through, they suddenly exclaim, "Aha! I found it! It was right there!"

The colleague shrugs and says, "Glad I could help!""""
          ),
        ],
        role='model'
      ),
      finish_reason=<FinishReason.STOP: 'STOP'>,
      index=0
    ),
  ],
  model_version='gemini-2.5-flash',
  response_id='j6a-aOm0JtfivdIP183q0AM',
  sdk_http_response=HttpResponse(
    headers=<dict len=11>
  ),
  usage_metadata=GenerateContentResponseUsageMetadata(
    candidates_token_count=133,
    prompt_token_count=6,
    prompt_tokens_details=[
      ModalityTokenCount(
        modality=<MediaModality.TEXT: 'TEXT'>,
        token_count=6
      ),
    ],
    thoughts_token_count=1780,
    total_token_count=1919
  )
)

In [28]:
response.text

'Why do programmers prefer dark mode?\n\nBecause bugs are attracted to light!\n\n---\n\nOr, a classic:\n\nA programmer is debugging some code. They\'ve been stuck for hours, unable to find the problem. Frustrated, they call over a colleague and say, "I\'ve tried everything! Can you just watch me walk through the code and tell me if you see anything?"\n\nThe programmer starts explaining the code line by line, detailing the logic and variables. About halfway through, they suddenly exclaim, "Aha! I found it! It was right there!"\n\nThe colleague shrugs and says, "Glad I could help!"'

In [29]:
print(response.text)

Why do programmers prefer dark mode?

Because bugs are attracted to light!

---

Or, a classic:

A programmer is debugging some code. They've been stuck for hours, unable to find the problem. Frustrated, they call over a colleague and say, "I've tried everything! Can you just watch me walk through the code and tell me if you see anything?"

The programmer starts explaining the code line by line, detailing the logic and variables. About halfway through, they suddenly exclaim, "Aha! I found it! It was right there!"

The colleague shrugs and says, "Glad I could help!"

In [30]:
def ask_llm(prompt):
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    return response.text

ask_llm("Du är en Göteborgare, ge mig ett skämt som är go")

'Jaha, du vill ha ett riktigt go\'tt göteborgsskämt, då? Ja, det ska du få!\n\nVet du vad? Det var en gubbe som var på Liseberg, som man ju är ibland. Och han var så himla duktig på att snurra på hjul och kasta bollar, så han vann en sån där *rejäl* chokladkaka, du vet en sån där gigantisk en.\n\nNär han sen ska hem på spårvagnen, så sitter han där med sin kaka, och en annan gubbe bredvid tittar på den och säger:\n"Gôtt med choklad va?"\n\nDå svarar göteborgaren:\n"Ja, men hur ska jag kunna *gå av* vagnen med den här, den är ju för stor för dörren!"\n\nDär har du en go gôteborgare som är mer bekymrad över logistiken än njutningen, la. Va? Goa\'re än så blir det inte!'

In [31]:
response = ask_llm("""
    Du är en expert inom köp och sälj av bostäder, likt en proffsig mäklare.
    Generera bostadspriser, månadsavgifter, address, stad, boarea i jsonformat (ej markdown)

    Exempel:
            {
                "address": "Fågelvägen 5,
                "price_sek": 3000000,
                "city": "Göteborg",
                "monthly_fee": 4000,
                "area": 60
            }   
                   
    Ge mig en lista på 5 bostäder
""")

response

'[\n    {\n        "address": "Karlaplan 10, Stockholm",\n        "price_sek": 7500000,\n        "city": "Stockholm",\n        "monthly_fee": 3800,\n        "area": 65\n    },\n    {\n        "address": "Linnégatan 25, Göteborg",\n        "price_sek": 4800000,\n        "city": "Göteborg",\n        "monthly_fee": 3200,\n        "area": 55\n    },\n    {\n        "address": "Västra Hamngatan 7, Malmö",\n        "price_sek": 3500000,\n        "city": "Malmö",\n        "monthly_fee": 4500,\n        "area": 75\n    },\n    {\n        "address": "Sysslomansgatan 15, Uppsala",\n        "price_sek": 2950000,\n        "city": "Uppsala",\n        "monthly_fee": 2900,\n        "area": 50\n    },\n    {\n        "address": "Ågatan 12, Linköping",\n        "price_sek": 2200000,\n        "city": "Linköping",\n        "monthly_fee": 3600,\n        "area": 70\n    }\n]'

In [32]:
print(response)

[
    {
        "address": "Karlaplan 10, Stockholm",
        "price_sek": 7500000,
        "city": "Stockholm",
        "monthly_fee": 3800,
        "area": 65
    },
    {
        "address": "Linnégatan 25, Göteborg",
        "price_sek": 4800000,
        "city": "Göteborg",
        "monthly_fee": 3200,
        "area": 55
    },
    {
        "address": "Västra Hamngatan 7, Malmö",
        "price_sek": 3500000,
        "city": "Malmö",
        "monthly_fee": 4500,
        "area": 75
    },
    {
        "address": "Sysslomansgatan 15, Uppsala",
        "price_sek": 2950000,
        "city": "Uppsala",
        "monthly_fee": 2900,
        "area": 50
    },
    {
        "address": "Ågatan 12, Linköping",
        "price_sek": 2200000,
        "city": "Linköping",
        "monthly_fee": 3600,
        "area": 70
    }
]

In [33]:
print(type(response))
print(response)

<class 'str'>
[
    {
        "address": "Karlaplan 10, Stockholm",
        "price_sek": 7500000,
        "city": "Stockholm",
        "monthly_fee": 3800,
        "area": 65
    },
    {
        "address": "Linnégatan 25, Göteborg",
        "price_sek": 4800000,
        "city": "Göteborg",
        "monthly_fee": 3200,
        "area": 55
    },
    {
        "address": "Västra Hamngatan 7, Malmö",
        "price_sek": 3500000,
        "city": "Malmö",
        "monthly_fee": 4500,
        "area": 75
    },
    {
        "address": "Sysslomansgatan 15, Uppsala",
        "price_sek": 2950000,
        "city": "Uppsala",
        "monthly_fee": 2900,
        "area": 50
    },
    {
        "address": "Ågatan 12, Linköping",
        "price_sek": 2200000,
        "city": "Linköping",
        "monthly_fee": 3600,
        "area": 70
    }
]

# Parse and validate data>

In [34]:
response

'[\n    {\n        "address": "Karlaplan 10, Stockholm",\n        "price_sek": 7500000,\n        "city": "Stockholm",\n        "monthly_fee": 3800,\n        "area": 65\n    },\n    {\n        "address": "Linnégatan 25, Göteborg",\n        "price_sek": 4800000,\n        "city": "Göteborg",\n        "monthly_fee": 3200,\n        "area": 55\n    },\n    {\n        "address": "Västra Hamngatan 7, Malmö",\n        "price_sek": 3500000,\n        "city": "Malmö",\n        "monthly_fee": 4500,\n        "area": 75\n    },\n    {\n        "address": "Sysslomansgatan 15, Uppsala",\n        "price_sek": 2950000,\n        "city": "Uppsala",\n        "monthly_fee": 2900,\n        "area": 50\n    },\n    {\n        "address": "Ågatan 12, Linköping",\n        "price_sek": 2200000,\n        "city": "Linköping",\n        "monthly_fee": 3600,\n        "area": 70\n    }\n]'

In [35]:
import json

json.loads(response)

[{'address': 'Karlaplan 10, Stockholm',
  'price_sek': 7500000,
  'city': 'Stockholm',
  'monthly_fee': 3800,
  'area': 65},
 {'address': 'Linnégatan 25, Göteborg',
  'price_sek': 4800000,
  'city': 'Göteborg',
  'monthly_fee': 3200,
  'area': 55},
 {'address': 'Västra Hamngatan 7, Malmö',
  'price_sek': 3500000,
  'city': 'Malmö',
  'monthly_fee': 4500,
  'area': 75},
 {'address': 'Sysslomansgatan 15, Uppsala',
  'price_sek': 2950000,
  'city': 'Uppsala',
  'monthly_fee': 2900,
  'area': 50},
 {'address': 'Ågatan 12, Linköping',
  'price_sek': 2200000,
  'city': 'Linköping',
  'monthly_fee': 3600,
  'area': 70}]

In [36]:
from pydantic import BaseModel, Field
import json 

class Apartment(BaseModel):
    address: str 
    city: str 
    price_sek: int = Field(gt=1000000, lt = 8000000) 
    monthly_fee: int 
    area: int 

class ApartmentList(BaseModel):
    objects: list[Apartment]

apartments = ApartmentList.model_validate({"objects": json.loads(response)})
apartments

ApartmentList(objects=[Apartment(address='Karlaplan 10, Stockholm', city='Stockholm', price_sek=7500000, monthly_fee=3800, area=65), Apartment(address='Linnégatan 25, Göteborg', city='Göteborg', price_sek=4800000, monthly_fee=3200, area=55), Apartment(address='Västra Hamngatan 7, Malmö', city='Malmö', price_sek=3500000, monthly_fee=4500, area=75), Apartment(address='Sysslomansgatan 15, Uppsala', city='Uppsala', price_sek=2950000, monthly_fee=2900, area=50), Apartment(address='Ågatan 12, Linköping', city='Linköping', price_sek=2200000, monthly_fee=3600, area=70)])

In [37]:
apartments.objects

[Apartment(address='Karlaplan 10, Stockholm', city='Stockholm', price_sek=7500000, monthly_fee=3800, area=65),
 Apartment(address='Linnégatan 25, Göteborg', city='Göteborg', price_sek=4800000, monthly_fee=3200, area=55),
 Apartment(address='Västra Hamngatan 7, Malmö', city='Malmö', price_sek=3500000, monthly_fee=4500, area=75),
 Apartment(address='Sysslomansgatan 15, Uppsala', city='Uppsala', price_sek=2950000, monthly_fee=2900, area=50),
 Apartment(address='Ågatan 12, Linköping', city='Linköping', price_sek=2200000, monthly_fee=3600, area=70)]

In [38]:
apartments.objects[1].address, apartments.objects[1].city

('Linnégatan 25, Göteborg', 'Göteborg')

## Gör en list comprehension för att få ut alla adresser

In [ ]:
addresses = [apartment.address for apartment in apartments.objects ]

addresses

['Karlaplan 10, Stockholm',
 'Linnégatan 25, Göteborg',
 'Västra Hamngatan 7, Malmö',
 'Sysslomansgatan 15, Uppsala',
 'Ågatan 12, Linköping']

In [42]:
addresses_less_than_4m = [
    apartment.address
    for apartment in apartments.objects
    if apartment.price_sek < 4000000
]

addresses_less_than_4m

['Västra Hamngatan 7, Malmö',
 'Sysslomansgatan 15, Uppsala',
 'Ågatan 12, Linköping']

### Get address, city, price, monthly_fee for the interval 4M - 8M

# ANNAT OCH ENKLARE SÄTT

In [47]:
import pandas as pd

# Filter
filtered_homes = [
    home for home in apartments.objects if 4_000_000 < home.price_sek < 8_000_000
]

filtered_homes

[Apartment(address='Karlaplan 10, Stockholm', city='Stockholm', price_sek=7500000, monthly_fee=3800, area=65),
 Apartment(address='Linnégatan 25, Göteborg', city='Göteborg', price_sek=4800000, monthly_fee=3200, area=55)]

# CONVERT TO DATAFRAME

In [48]:
# Convert to df
df_homes_filtered = pd.DataFrame(
    [
        home.model_dump(include={"address", "city", "price_sek", "monthly_fee"})
        for home in filtered_homes
    ]
)

df_homes_filtered

                   address       city  price_sek  monthly_fee
0  Karlaplan 10, Stockholm  Stockholm    7500000         3800
1  Linnégatan 25, Göteborg   Göteborg    4800000         3200

In [49]:
df_homes_filtered.to_csv("filtered_homes.csv", index=False)

## save to json - serialize pydantic model

In [50]:
apartments

ApartmentList(objects=[Apartment(address='Karlaplan 10, Stockholm', city='Stockholm', price_sek=7500000, monthly_fee=3800, area=65), Apartment(address='Linnégatan 25, Göteborg', city='Göteborg', price_sek=4800000, monthly_fee=3200, area=55), Apartment(address='Västra Hamngatan 7, Malmö', city='Malmö', price_sek=3500000, monthly_fee=4500, area=75), Apartment(address='Sysslomansgatan 15, Uppsala', city='Uppsala', price_sek=2950000, monthly_fee=2900, area=50), Apartment(address='Ågatan 12, Linköping', city='Linköping', price_sek=2200000, monthly_fee=3600, area=70)])

In [51]:
# dictionary
apartments.model_dump()

{'objects': [{'address': 'Karlaplan 10, Stockholm',
   'city': 'Stockholm',
   'price_sek': 7500000,
   'monthly_fee': 3800,
   'area': 65},
  {'address': 'Linnégatan 25, Göteborg',
   'city': 'Göteborg',
   'price_sek': 4800000,
   'monthly_fee': 3200,
   'area': 55},
  {'address': 'Västra Hamngatan 7, Malmö',
   'city': 'Malmö',
   'price_sek': 3500000,
   'monthly_fee': 4500,
   'area': 75},
  {'address': 'Sysslomansgatan 15, Uppsala',
   'city': 'Uppsala',
   'price_sek': 2950000,
   'monthly_fee': 2900,
   'area': 50},
  {'address': 'Ågatan 12, Linköping',
   'city': 'Linköping',
   'price_sek': 2200000,
   'monthly_fee': 3600,
   'area': 70}]}

In [53]:
# str of json data
apartments.model_dump_json()

'{"objects":[{"address":"Karlaplan 10, Stockholm","city":"Stockholm","price_sek":7500000,"monthly_fee":3800,"area":65},{"address":"Linnégatan 25, Göteborg","city":"Göteborg","price_sek":4800000,"monthly_fee":3200,"area":55},{"address":"Västra Hamngatan 7, Malmö","city":"Malmö","price_sek":3500000,"monthly_fee":4500,"area":75},{"address":"Sysslomansgatan 15, Uppsala","city":"Uppsala","price_sek":2950000,"monthly_fee":2900,"area":50},{"address":"Ågatan 12, Linköping","city":"Linköping","price_sek":2200000,"monthly_fee":3600,"area":70}]}'

## SKAPA JSON-fil

In [54]:
with open("apartments.json", "w") as json_file:
    json_file.write(apartments.model_dump_json(indent=3))

In [70]:
addresses = [apartment.address for apartment in apartments.objects]
prices = [apartment.price_sek for apartment in apartments.objects]
monthly_fees = [apartment.monthly_fee for apartment in apartments.objects]
areas = [apartment.area for apartment in apartments.objects]

df = pd.DataFrame(
    {"adress": addresses, "area": areas, "price": prices, "monthly_fee": monthly_fees}
    )

df

                        adress  area    price  monthly_fee
0      Karlaplan 10, Stockholm    65  7500000         3800
1      Linnégatan 25, Göteborg    55  4800000         3200
2    Västra Hamngatan 7, Malmö    75  3500000         4500
3  Sysslomansgatan 15, Uppsala    50  2950000         2900
4         Ågatan 12, Linköping    70  2200000         3600

## put data into a duckdb databse

Approach 1
- duckdb read.csv_auto....

Approach 2
- open up a connection to duckdb
- create scehma
- create tables from df 

Approach 3 (naive)
- create tables
- insert data manually or parse with python

Approach 4 - dlt (DETTA KÖR VI PÅ)
- extract and load df into duckdb

In [ ]:
# uv pip install dbt[duckdb] i terminal
import dlt

@dlt.resource(write_disposition="replace", table_name="apartment")
def load_data():
    yield df

pipeline = dlt.pipeline(
    pipeline_name="apartments",
    destination="duckdb", 
    dataset_name="staging"
)

load_info = pipeline.run(load_data())
print(load_info)

Pipeline apartments load step completed in 0.13 seconds
1 load package(s) were loaded to destination duckdb and into dataset staging
The duckdb destination used duckdb:///c:\Users\henri\source\repos\Python\Objektorienterad programmering avancerad 1\ai_engineering_henrik_pilback\Code_alongs\07_pydantic\apartments.duckdb location to store data
Load package 1757331209.5849526 is LOADED and contains no failed jobs

## select * from staging.apartment;